### PR TITLE
Localisation system to translate game into other languages

### PR DESCRIPTION
**Pull request by Wohlstand**
This is the extensive work which introduces the multi-language system that makes the game translatable into multiple languages (the whole set of built-in strings, and soon, the sub-system of non-destructive translations for episodes, it wasn't made yet, still in work).

Related discussion: https://github.com/Wohlstand/TheXTech/discussions/340
Moondust side work: https://github.com/WohlSoft/Moondust-Project/issues/559

## To do:

- [x] Make the basic UI translation
- [x] Add the rest of the built-strings into the translation queue
- [x] Ensure there is a system that provides proper grammar for numbers (Slavic languages have single, dual, and plural numbers, and it has more complex rules than simple Roman singular/plural).
- ~~Implement the utility to generate/edit episode translation files (The ongoing work is at [Moondust Project](https://github.com/WohlSoft/Moondust-Project) repository).~~
  - ~~[x] Implement basic functionality (Scanning, loading, saving, translating)~~
  - ~~Implement the sub-system to indicate lines that needs an attention and fix the status displaying~~
  - ~~Finalise overlook~~ 
  - Moved to own issue: https://github.com/WohlSoft/Moondust-Project/issues/559
- [x] Implement the backend to load and apply episode translations
- [x] Implement the KEY-based translations system in addition to the absolute-index system. It's needed for new projects that intended to be rapidly changed, and being more convenient in the future for lua scripts where developers could make their "key=value strings database" and use key in their scripts.

If something missing, please add that.

### CODE REVIEW

**Comment by LoveBodhi** [comment]
So how about some english words like "Once, Twice, 1st, 2nd, etc"?

**Comment by LoveBodhi** [comment]
Touch Screen / 触屏：

- Layout Style 按键样式
> Standard 普通
> Tight 大号
> Tiny 小号（旧）
> Phone 手机（旧）
> Long 加长（旧）
> Phablet 大平板（旧）
> Tablet 平板（旧）

- Scale Factor 按键缩放
- Scale D-Pad 方向键缩放
- S-Start Spacing 选择/开始键间距
- Reset Layout 重置布局
- Interface Style 动作键样式
> ABXY
> XODA
> Actions 动作

- Feedback Strength 震动强度
- Feedback Length 震动时长
- Hold run on start 自动按住奔跑键
- Show Cheat Button 显示指令键

**Comment by ds-sloth** [comment]
A very exciting moment: I believe the only remaining non-translatable strings are in the editor.
If you find any, please let us know.

**Comment by LoveBodhi** [comment]
[TheXTech Editor CN Strings.txt](https://github.com/Wohlstand/TheXTech/files/11228604/TheXTech.Editor.CN.Strings.txt)

Might contain outdated or existing ZH-CN Localization.

**Comment by LoveBodhi** [comment]
The only issue of the language is Align, and the phrase `Next triggers when` (no more texts)

**Comment by LoveBodhi** [comment]
Oh my bad! Please convert to draft!

**Comment by LoveBodhi** [comment]
Scr_2023-05-04_11-41-55

The text should be right-aligned due to length-varied

**Comment by LoveBodhi** [comment]
Note: JSON's will not work if there's comment (`//JSON Comment Text`) inside.

**Comment by Wohlstand** [comment]
Comments are not supported by JSON at all. They COULD be implemented as a kind of custom "pre-processor", but they out of standard and never been supported by JSON in general.

**Comment by Wohlstand** [comment]
Okay, seems the thing is ready if not count the partially unfilled Russian translation file.

**Comment by Wohlstand** [comment]
I'll set this being ready for review. I'll fill the Russian translation soon.

**Comment by Wohlstand** [comment]
There are some things needed to be fixed:

- [ ] Alignment for the text of the right column for world map items: 
Снимок экрана от 2023-05-26 23-29-50

- [ ] Use the right alignment of tooltips when cursor is close to the right side of the screen to make them don't be hidden off screen:
Снимок экрана от 2023-05-26 23-41-16

- [ ] Clarify the max title length for the text input dialogue: 
Снимок экрана от 2023-05-26 23-44-41

Also, for the future (suitable for a new issue):
- Implement the layout toggling (a kind of "LANG" button that will cycle between internal list of layouts depending on current language, or from a pop-up list).

**Comment by ds-sloth** [comment]
Ah, yes, I had forgotten about the layout customization.

I'd like to set it up so that the text entry layout may be fully customized and loaded from a file. That could be a part of the translation's JSON file, or the layouts could be stored separately and specified by filename in the localization.

We could either include a QWERTY fallback layout inside of the localization's layout, or we could support an onscreen button for toggling between the localization-specific layout and the built-in QWERTY layout. Which would you prefer?

(As a side note, I have no plans to implement a full IME. I think it is out-of-scope for the project, but creators can use the desktop's text entry system on desktop SDL, and can also use the built-in keyboards on Android and 3DS.)

**Comment by Wohlstand** [comment]
Keep a note, there is NEEDED a togglability of layouts. I.e. have two-three layouts being available. Keyboards that use non-latin language, keep the ability to type latin by switching layout by a key combo (typically by Alt+Shift or configurable to Ctrl+Shift, Ctrl+Space, Super+Space etc.). That how we in Russia use keyboard. The ability to type latin characters is often need to... type foreign company names, game titles, terms, etc.

**Comment by ds-sloth** [comment]
These three issues should be fixed now, can you please confirm?

(Haven't made the keyboard layout customizability yet, but that could be done separately from this PR as you mentioned.)

**Comment by LoveBodhi** [comment]
So how does pinyin input (拼音输入法) work?

**Comment by LoveBodhi** [comment]
Scr_2023-06-01_08-33-06_1

Why not fix this (Layout of 友好 and 信息), which had been mentioned by me at before??

**Comment by ds-sloth** [comment]
Pinyin input could work on consoles to produce pinyin (same for zhuyin) but it would not be possible to convert them to hanzi (IME) because of the limited resources of the console ports.

It could be possible to make a keyboard layout with the most common hanzi but it would probably be hard to use.

On 3DS (and possibly Switch in the future) it is possible to use the system's built in keyboard which may include an IME (I don't remember).

For the note on editor text layout, that is a useful suggestion but I didn't have enough time to fix it yet. If you make a separate issue I will be certain to fix it before the 1.3.6.1 release.

**Comment by Wohlstand** [comment]
On Switch it's really possible to call the system keybaord and type on any language that it provides.

**Pull request merged**
