### PR TITLE
Make speedrun timer be more colorful

### PR DESCRIPTION
**Pull request by Wohlstand**
This update makes the speed-run timer being more colorful when it stops at the level end or episode complete events.

Scr_2022-03-18_03-16-11
Scr_2022-03-18_03-13-54

Any ideas/suggestions/objections?

### CODE REVIEW

**Comment by Wohlstand** [comment]
> Coloring/Blinking should be optional via an [effects] or [speedrun] entry in settings.ini/compat.ini: enable-timer-effects. It should have 3 options:

I guess, there is need the fourth `undefined` value and the priority:
- compat.ini by default sets one of values (enable/disable/opaque) by default
- settings/thextech.ini sets the "unspecified" by default, meaning, episode-side config is preferred
- when settings/thextech.ini defines anything also than "unspecified", it will have highest priority over compat.ini, means user has different wish against the look

**Comment by ds-sloth** [comment]
Ah, this is a great effect! Very simple, really nice to look at. I agree with @0lhi that it's probably a good idea to enable by default only if the user chose opaque speedrun timer.

> I guess, there is need the fourth undefined value and the priority

After we merge multires + in-game editor, my next goal is the big compat / config rewrite we have been talking about so that we don't need to think about these anymore. :)

The code is clean and simple. No reason not to merge it in my opinion. :100:

**Comment by 0lhi** [comment]
*true*, *false*, and *opaque* settings all work as intended.

Didn't bother to test with compat.ini, cause imo we should wait until the big rewrite before encouraging it's use.

**Comment by Wohlstand** [comment]
> Didn't bother to test with compat.ini, cause imo we should wait until the big rewrite before encouraging it's use.

compat.ini-side option will work when the settings/thextech.ini side is set into `undefined`

**Comment by Wohlstand** [comment]
Going to merge this as seems, all fine now.

**Pull request merged**
