### PR TITLE
Show collected stars per level at world map

### PR DESCRIPTION
**Pull request by Wohlstand**
All changes was done without WLDX new fields yet, will add them later

### CODE REVIEW

**Comment by ds-sloth** [comment]
I'm not sure that this should be the default behavior.

In many episodes (like Invasion 2) it is unknown which levels have stars. I would by default only print the number of obtained stars, not the number of available stars. There could be a wldx setting that allows to print number of available stars. How does that sound to you?

**Comment by 0lhi** [comment]
Shared my Take in the Moondust Chatroom, gonna paste here:

>Oh no, I strongly think that it should be turned on by default :o It is the case for Hubworld Episodes already, and no-one sees Spoilers as a concern there
>
>Plenty of people that I introduced to The Invasion 2 were turned away by it's confusion Map Layout, and ended up staying away from SMBX as a consequence
>
>The Star Locations being hidden does contribute to that confusion
>
>It's why I currently recommend people new to SMBX to start with "Super RMN World", because there it's clear how many stars are where
>
>People who want to get the Vanilla Experience can just turn to Mode 2 or 3. Afterall, that's what they are there for
>
>But TheXTech as a whole shouldn't suffer from the limitations of Vanilla SMBX. Lack of Star Display is rarely an intentional decision, but almost always a consequence of it's limitations.

**Comment by ds-sloth** [comment]
From the chat it seems that everyone wants to have the number of acquired stars shown by default and the question is whether the number of available stars should be shown by default. It's clear from our level of disagreement that this should be a settable config option (show or don't show star locations) with both available for the modern game and the question is which setting should be on by default for the modern game.

My philosophy behind modern mode is that it should be the best way to experience the gameplay of SMBX, with modifications that make it look better and feel more modern or provide the player with information they already have, but without altering the overall experience of the game. I see showing the star locations as a core experience modification, similar to adding spin jumps to characters or adding ground pound without the correct yoshi.

If the star locations in an episode are too confusing, that might be a problem with the episode, but the creator of the episode made the decision to hide the stars (as they are hidden in many of the games that inspired SMBX and TheXTech). I do think that at least in the games that inspired SMBX, not displaying star locations (or warp cannon locations, later on) was completely intentional.

From my perspective, a lot of the excitement of episodes like The Invasion 2 is in finding the hidden stars. I don't think that effectively adding a walkthrough by default would improve most users' experience, especially given that it's almost never required for a user to find any stars in the episodes where they are hidden. (And if it is, that's a major design flaw with the episode but not our job to fix by default.)

I propose that we should set up some sort of poll to figure out the default. Should we do that on GitHub or on Discord? (Preferably both, but I'm not sure how to merge them.)

**Comment by Wohlstand** [comment]
Okay, I had to extend the functionliaty of this mechanism, and now there are many ways to set up the showing of colelcted stars:
- per level individually
- per whole world map
- per compat.ini
- and the last - by settings/thextech.ini

**Comment by 0lhi** [comment]
> My philosophy behind modern mode is that it should be the best way to experience the gameplay of SMBX [...] but without altering the overall experience of the game.

I see a contradiction there. The Vanilla Engine has many flaws, so the best experience entails Changes. It's why many Compat-Fixes are enabled by default. This would just be another one on the list.

> If the star locations in an episode are too confusing, that might be a problem with the episode, but the creator of the episode made the decision to hide the stars

In most cases I think it was just not caring to make a Star Tracking Level (which is bothersome) rather than the active decision to hide. The Original Issue #156 I made was because of the NSMB DS Remake, which is an example for that. In The Invasion 2, you can already check the Map's Star Entrances by entering the doors in Rosalina's Place, so for this episode, the Change seems more like a Quality-of-Life thing to me, similar to *enable-last-warp-hub-resume*, rather than a Spoiler.

> I do think that at least in the games that inspired SMBX, not displaying star locations (or warp cannon locations, later on) was completely intentional.

Umm, can you name some examples? Warp Zones are one thing. There weren't any Stars in the old 2D Marios, but the Map did share which levels contained Secret Exits. Mario 64 does share most of the Star Locations. Secret Stars are an exception, but in the case of those, the levels themselves are hidden. So, the Analogy for SMBX would be revealing the Map Path before unlocking it, which I do not want.

> From my perspective, a lot of the excitement of episodes like The Invasion 2 is in finding the hidden stars. I don't think that effectively adding a walkthrough by default would improve most users' experience

Walkthrough is too big a word. The Secret Exits are announced on the Map, but it's still up to you to find them. Same would be the case for the Stars. All it does is removing the guess work on which level contains how many.

> (And if it is, that's a major design flaw with the episode but not our job to fix by default.)

I mean, nothing we do here is our Job. We contribute voluntarily to improve the Playing Experience. This change in particular has the potential to turn countless of bad episodes into good episodes by changing one single detail. That seems like a pretty good deal to me.

> I propose that we should set up some sort of poll to figure out the default. Should we do that on GitHub or on Discord? (Preferably both, but I'm not sure how to merge them.)

You mentioned your Philosophy above. My philosophy / source of motivation is to make SMBX as accessible and inviting as possible. I think an intuitive experience is critical for that, and my observations so far have confirmed this.

A Poll that matches the preference of people who are already inside the SMBX Community may not represent what would make TheXTech appealing to New Users. So, I think the default should be decided by debate rather than a vote.

**Comment by ds-sloth** [comment]
> A Poll that matches the preference of people who are already inside the SMBX Community may not represent what would make TheXTech appealing to New Users. So, I think the default should be decided by debate rather than a vote.

I can get behind this. I similarly prefer to discuss until consensus is reached.

> I see a contradiction there. The Vanilla Engine has many flaws, so the best experience entails Changes. It's why many Compat-Fixes are enabled by default. This would just be another one on the list.

I see a continuum between (1) things like fixing bugs and changing the level resolution and (2) altering the rules of the game / the way a player approaches the game. In our past discussions, I have often been more hesitant to change the gameplay (such as preferring not to allow repeated drop/add without costing lives) than some of the other community members.

One option to resolve these competing philosophies would be to offer users, upon first boot, three experiences -- "modern gameplay", "preserved gameplay", "preserved everything" -- with corresponding sets of default compat values and gameplay settings. I don't know how that would strike the other people in this discussion.

**Comment by Wohlstand** [comment]
Note: default global behavior is: showing is disabled, user will be able to enable this by settings/thextech.ini or by compat.ini, or later by WLDX (when I will implement Editor-side fields binding, `$%@&` my 2014's code...)

**Comment by 0lhi** [comment]
> One option to resolve these competing philosophies would be to offer users, upon first boot, three experiences -- "modern gameplay", "preserved gameplay", "preserved everything" -- with corresponding sets of default compat values and gameplay settings. I don't know how that would strike the other people in this discussion.

Great idea! Who are we to decide which approach is the correct one? Letting the user choose at first boot is the way to go 👍

It reminds me a bit of the [Difficulty Mode](https://github.com/Wohlstand/TheXTech/issues/37#issuecomment-781045111) that I brought up in Wohl's Game Over thread. Maybe the approaches could be combined somehow?

I think, the question on how to do this in detail warrants a new GitHub Discussion. But it's definitely the direction we should take.

**Comment by ds-sloth** [comment]
> It reminds me a bit of the Difficulty Mode that I brought up in Wohl's Game Over thread. Maybe the approaches could be combined somehow?
I agree wholeheartedly. Start 5, max 999 lives (or even casual mode?) seems like a clear default for the "modern gameplay" version. (Casual mode makes kaizo episodes actually somewhat reasonable... :) )

In any case, @Wohlstand, I approve of the changes you proposed in this PR. Let's move discussion of default options to a GitHub Discussion for the future, since it seems that the discussion is becoming increasingly broad in scope.

**Comment by Wohlstand** [comment]
> In any case, @Wohlstand, I approve of the changes you proposed in this PR. Let's move discussion of default options to a GitHub Discussion for the future, since it seems that the discussion is becoming increasingly broad in scope.

Right, so, gonna merge this. :fox_face: :+1:

**Pull request merged**
