### PR TITLE
Keyhole animation ready for testing

### PR DESCRIPTION
**Pull request by ds-sloth**
Should be a quick test but wanted to do it via a PR so the implementation could be reviewed. How does it look?

### CODE REVIEW

**Review by Wohlstand — COMMENTED** [review]
By a quick look, seems fine, I should check this more carefully sooner.

**Comment by ds-sloth** [comment]
Before we merge, I just realized: (1) there isn't a compat guard or changelog entry for the animation, and (2) the animation doesn't work perfectly when the keyhole framerate fix is disabled.

**Comment by 0lhi** [comment]
I think for now you can just disable the animation when `fix-keyhole-framerate = false`, no reason to introduce another flag for this.

**Comment by Wohlstand** [comment]
> the animation doesn't work perfectly when the keyhole framerate fix is disabled.

You should use the floating iterator for that. That's a way to perform a variadic-framerate update.

**Comment by ds-sloth** [comment]
I thought I was already properly adjusting the framerate. It's probably a silly fix -- I'll take a look now.

Anyway, I wonder if we should just re-use the keyhole framerate flag and decide which flag to use permanently when merging the config branch in the future.

**Comment by ds-sloth** [comment]
Fixed that the !fix_keyhole_framerate issue -- turns out that the entire UpdateGraphics call was being cancelled by a frameskip. The fix_keyhole_framerate workaround didn't update the fields used by the new frameskip code. So I disabled frameskip during the keyhole exit macro if the fix_keyhole_framerate was off.

I also added documentation, and a compat guard for the feature. So I think we are now ready to go if the code looks good to you.

**Review by Wohlstand — APPROVED** [review]
I checked the thing, and I made some small tweaks at the gfx_update to simplify the condition. So, I going to merge this.

**Pull request merged**
