### PR TITLE
Added sound FX per section (echo and reverb effects)

### PR DESCRIPTION
**Pull request by Wohlstand**
This update adds the next features:
- SPC-like echo effect (the echo algorithm was taken from the SPC emulator directly and adapted to be a general-purpose sound FX module)
- Simple reverb effect

These options currently can be set by sounds.ini with new-added sections.

There are two ways to add an effect:
- Direct adding:
```ini
[section-fx-0]
fx = echo
echo-on = 1
delay = 2
feedback = 25
main-volume-left = 127
main-volume-right = 127
echo-volume-left = 20
echo-volume-right = 20
fir-0 = 15
fir-1 = -92
fir-2 = -46
fir-3 = -64
fir-4 = 14
fir-5 = -64
fir-6 = -88
fir-7 = -76
```
Where 0 - the number of sections based from 0

- Aliasing (Useful to make global effects and simply re-use them at levels of episode. This allows you to tune up the same effect as you want)
```ini
[fx-bonusroom]
fx = echo
echo-on = 1
delay = 2
feedback = 25
main-volume-left = 127
main-volume-right = 127
echo-volume-left = 20
echo-volume-right = 20
fir-0 = 15
fir-1 = -92
fir-2 = -46
fir-3 = -64
fir-4 = 14
fir-5 = -64
fir-6 = -88
fir-7 = -76

; ...

[section-fx-0]
custom-fx = bonusroom
```

## New-added sounds.ini options:
```ini
[fx-<name>]   ; <name> - the name of the effect
fx = echo     ; possible: 'none' / 'echo' / 'reverb'
; Echo-only options
echo-on = 1   ; Enable echo effect
delay = 6        ; Delay of the echo effect
feedback = 52   ; Echo feedback
main-volume-left = 127         ; Left volume of main output (between -127 and +127)
main-volume-right = 127       ; Right volume of main output (between -127 and +127)
echo-volume-left = 14           ; Left volume of echo output (between -127 and +127)
echo-volume-right = 12        ; Left volume of echo output (between -127 and +127)
fir-0 = 99                                ; FIR filter, step 1 value (between -127 and +127)
fir-1 = -7                                ; FIR filter, step 2 value
fir-2 = 32                                ; FIR filter, step 3 value
fir-3 = 50                                ; FIR filter, step 4 value
fir-4 = 25                                ; FIR filter, step 5 value
fir-5 = 51                                ; FIR filter, step 6 value
fir-6 = -35                                ; FIR filter, step 7 value
fir-7 = 56                                ; FIR filter, step 8 value
; Reverb-only options
mode = 0           ; Reverb mode: 0 - normal, 1 - freezing
room-size = 0.7 ; Reverb room size
damping = 0.5   ; Damping (from 0.00 to 1.00 basicly, possible to excite this limit, precission is not limited)
wet-level = 0.2   ; Wet level (from 0.00 to 1.00 basicly, possible to excite this limit, precission is not limited)
dry-level = 0.4   ; Dry level (from 0.0 to 1.0 basicly, possible to excite this limit, precission is not limited)
width = 1.0        ; Width (from 0.00 to 1.00 basicly, possible to excite this limit, precission is not limited)

[section-fx-XXXX] ; where XXXX - 0-based section number
custom-fx = <name>  ; reuse one of globally added effects
fx = echo     ; possible: 'none' / 'echo' / 'reverb'
; When "custom-fx" is set, no other options needed
; when "fx" used, options were are same as for `[fx-<name>] ` section
```

## Short demo

https://user-images.githubusercontent.com/6751442/151594591-2256cb17-ac66-4d04-ae6e-c6626300c6aa.mp4

### CODE REVIEW

**Comment by LoveBodhi** [comment]
LPF should be added, too (For in the water).

**Comment by Wohlstand** [comment]
Btw, @0lhi , a small demo to test the thing in action:

[sound-fx-demo.zip](https://github.com/Wohlstand/TheXTech/files/7963943/sound-fx-demo.zip)

**Comment by Wohlstand** [comment]
Just now I updated reverb code, now it uses https://github.com/sinshu/freeverb as backend. So, parameters for reverb got changed:
```ini
fx = reverb
mode = 0        ; 0 - normal, 1 - freezing
room-size = 0.7
damping = 0.5
wet-level = 0.2
dry-level = 0.4
width = 1.0
```

**Comment by Wohlstand** [comment]
BTW: For the future, there are some next things can be done after merge
- Allow Autocode and by event command to enable/disable/toggle effect (by name) at specific section to make an ability to dynamically switch the effect if needed (for example, when player enters/quits the building at the same section)
- Add low-pass and some other filters (being applied before or after main effect by user's choice)
- Try to make effects and filters to be assigned with music only or SFX, not just the whole audio stream

**Comment by ds-sloth** [comment]
I've skimmed the files and they look good. Let's merge it!

**Pull request merged**
